const initialState = {
  displayEnrolled: false,
  enrolled: {
      '1': {
        date: '2/10/2016',
        enrolled: 'true',
        firstName: 'Kafka',
        lastName: 'Tamura',
        gender: 'male',
        dob: '1/1/2000',
        programId: '1',
        programLocation: 'Cape Town',
        programCategory: 'Youth Empowerment',
        programType: 'Internship',
        dates: 'May 22 - June 16',
        university: 'UCLA',
        fieldOfStudy: 'Chemistry',
        recruitmentMethod: 'campaign',
        refcode: 'C296',
        passport: 'USA',
      },
      '2': {
        date: '3/11/2016',
        enrolled: 'true',
        firstName: 'John',
        lastName: 'Blake',
        gender: 'male',
        dob: '2/2/1999',
        programId: '2',
        programLocation: 'Jamaica',
        programCategory: 'Youth Empowerment',
        programType: 'Internship',
        dates: 'July 10 - August 4',
        university: 'UCI',
        fieldOfStudy: 'Biology',
        recruitmentMethod: 'website',
        refcode: 'health',
        passport: 'USA',
      },
      '3': {
        date: '4/12/2016',
        enrolled: 'true',
        firstName: 'Elaine',
        lastName: 'Rosco',
        gender: 'female',
        dob: '3/3/1998',
        programId: '3',
        programLocation: 'Cape Town',
        programCategory: 'Youth Empowerment',
        programType: 'Volunteer Program',
        dates: 'May 22 - June 2',
        university: 'UCSB',
        fieldOfStudy: 'Math',
        recruitmentMethod: 'website',
        refcode: 'health',
        passport: 'USA',
      },
      '4': {
        date: '4/12/2016',
        enrolled: 'true',
        firstName: 'Kaiya',
        lastName: 'Malaika',
        gender: 'female',
        dob: '4/4/1997',
        programId: '4',
        programLocation: 'Cape Town',
        programCategory: 'Health Innovation',
        programType: 'Volunteer Program',
        dates: 'June 5 - June 16',
        university: 'UCD',
        fieldOfStudy: 'Agriculture',
        recruitmentMethod: 'website',
        refcode: 'health',
        passport: 'USA',
      },
      '5': {
        date: '4/12/2016',
        enrolled: 'true',
        firstName: 'Roger',
        lastName: 'Meadows',
        gender: 'male',
        dob: '5/5/1996',
        programId: '5',
        programLocation: 'Jamaica',
        programCategory: 'Youth Empowerment',
        programType: 'Volunteer Program',
        dates: 'July 10 - July 21',
        university: 'UCSF',
        fieldOfStudy: 'Medicine',
        recruitmentMethod: 'website',
        refcode: 'health',
        passport: 'USA',
      },
      '6': {
        date: '4/12/2016',
        enrolled: 'true',
        firstName: 'Steven',
        lastName: 'Brown',
        gender: 'male',
        dob: '6/6/1995',
        programId: '6',
        programLocation: 'Cape Town',
        programCategory: 'Health Innovation',
        programType: 'Internship',
        dates: 'July 31 - August 25',
        university: 'UCSF',
        fieldOfStudy: 'Medicine',
        recruitmentMethod: 'website',
        refcode: 'health',
        passport: 'USA',
      }
    }
}

module.exports = initialState

// will need seperate list for Applicant / Accepted / Enrolled
